version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=webapp.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-me
    volumes:
      - pdf_uploads:/app/uploads
      - pdf_results:/app/results
      - pdf_logs:/app/logs
    restart: always

volumes:
  pdf_uploads:
  pdf_results:
  pdf_logs: